# Generated by Django 3.2.7 on 2021-10-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20211008_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nb_services_given',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nb_services_received',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
