# Generated by Django 3.2.7 on 2021-12-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20211029_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_bio',
            field=models.CharField(max_length=650, null=True),
        ),
    ]
