# Generated by Django 3.2.7 on 2021-12-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_alter_userinfo_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
