# Generated by Django 3.2.7 on 2021-09-19 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.CharField(default='Administration', max_length=30)),
                ('description', models.CharField(default='Aucune description', max_length=100, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('max_distance', models.PositiveIntegerField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
