# Generated by Django 3.2.7 on 2021-09-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='User',
            new_name='user',
        ),
    ]
