# Generated by Django 3.2.7 on 2021-10-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_rename_user_offer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='dimanche',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='jeudi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='lundi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='mardi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='mercredi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='samedi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='vendredi',
            field=models.BooleanField(default=False),
        ),
    ]
