# Generated by Django 3.2.7 on 2021-10-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20211006_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
