# Generated by Django 3.2.7 on 2021-10-07 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_alter_offer_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
