# Generated by Django 3.2.7 on 2021-10-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_offer_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
