# Generated by Django 3.2.7 on 2021-10-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_alter_offer_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
