# Generated by Django 3.2.7 on 2021-10-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_alter_offer_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='vendredi',
            new_name='friday',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='lundi',
            new_name='monday',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='samedi',
            new_name='saturday',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='dimanche',
            new_name='sunday',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='jeudi',
            new_name='thursday',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='mardi',
            new_name='tuesday',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='mercredi',
            new_name='wednesday',
        ),
    ]
