# Generated by Django 3.2.7 on 2021-10-28 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0008_auto_20211011_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.offer')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TerminatedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('rating', models.FloatField(null=True)),
                ('id_active_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.activeoffer')),
                ('id_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.offer')),
                ('id_recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_terminated_offer', to=settings.AUTH_USER_MODEL)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_terminated_offer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(null=True)),
                ('id_active_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.activeoffer')),
                ('id_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.offer')),
                ('id_recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_reserved_offer', to=settings.AUTH_USER_MODEL)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_reserved_offer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
