# Generated by Django 3.2.7 on 2021-10-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_servicetype'),
        ('offer', '0010_alter_terminatedoffer_status'),
    ]

    operations = [
    ]
