# Generated by Django 3.2.7 on 2021-11-01 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_merge_20211031_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminatedoffer',
            name='id_active_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.activeoffer'),
        ),
    ]
