# Generated by Django 3.2.7 on 2021-11-01 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_alter_terminatedoffer_id_active_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminatedoffer',
            name='id_active_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.activeoffer'),
        ),
    ]
