# Generated by Django 3.2.7 on 2021-11-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_alter_terminatedoffer_id_active_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='expiration_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
