# Generated by Django 3.2.7 on 2021-11-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_alter_terminatedoffer_id_active_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='starting_date',
            field=models.DateField(null=True),
        ),
    ]
