# Generated by Django 3.2.7 on 2021-11-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_offer_starting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='expiration_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='starting_date',
            new_name='start_date',
        ),
    ]
