# Generated by Django 3.2.7 on 2021-11-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_auto_20211117_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedoffer',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default='13.50', max_digits=6),
        ),
    ]
