# Generated by Django 3.2.7 on 2021-12-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0016_terminatedoffer_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(default='Aucune description', max_length=900, null=True),
        ),
    ]
